### ISSUE TITLE
Máy đào không hoạt động như mong muốn

### ISSUE THREAD

**Issue by nguyenmauchanh** [lesongvi/RQN9PCMiner#1]
Máy đào không hoạt động như mong muốn! Mong bạn sửa lỗi sớm hoặc cho ra mắt phần mềm MaxMinerMiner, tôi rất mong chờ phiên bản tiếp theo của ứng dụng hoăc một phần mềm mới tốt hơn!.

**Comment by lesongvi** [comment]
![rqn9pcminer still running](https://user-images.githubusercontent.com/20860845/159110790-17289462-da6c-4a9e-8ba4-854ee46093bb.png)
Máy đào vẫn hoạt động tốt, bạn vui lòng kiểm tra lại mạng internet tại khu vực bạn đang ở.
